// Danh sách nhân vật (tự thiết kế, không mô phỏng người thật).
// Mỗi nhân vật ghép từ các bộ phận dùng chung: kiểu tóc, mũ, phụ kiện mặt, trang phục.
//   skin  màu da · hair màu tóc · top áo · bottom quần/váy · shoes giày
//   hairStyle  ahoge|short|spiky|messy|slick|bob|long|wavy|bun|mohawk|pigtails|bald
//   hat        nonla|ninja|bubble|hood|helmet|fullhelmet|cap|capBack|chef|crown|tiara|tricorn|santa|fire|band|mirror|turban|veil|phones|scarfHead|beanie
//   face       danh sách: glasses|shades|mustache|curly|beard|patch|freckles|fangs|blush
//   sleeve 0..1 độ dài tay áo · pants 0..1 độ dài ống quần · arms/legs màu tay/chân bên trong
//   extra      dress|aodai|coat|cape|apron|scarf|tie|pack|box|belly|chain|star|whistle|collar|belt|badge
export const CHARS = [
  { id: 'tron', name: 'Bé Đụt', emo: '🙂', skin: '#ffd2a6', hair: '#6b4426', top: '#ffc93d', bottom: '#2f8bff', shoes: '#ff4d6d', hairStyle: 'ahoge', sleeve: 0.3, pants: 0.35, face: ['blush'] },
  { id: 'hocsinh', name: 'Học Sinh', emo: '🎒', skin: '#fbcca6', hair: '#1d1648', top: '#ffffff', bottom: '#2a3a7a', shoes: '#1d1648', hairStyle: 'spiky', sleeve: 0.3, pants: 0.35, extra: { scarf: '#ff3d4f', pack: '#38b2ff' } },
  { id: 'cogiao', name: 'Cô Giáo', emo: '👩‍🏫', skin: '#fcd2b0', hair: '#2a1a14', top: '#fbfbff', bottom: '#fbfbff', shoes: '#c0392b', hairStyle: 'long', sleeve: 1, pants: 1, face: ['glasses'], extra: { aodai: '#fbfbff' } },
  { id: 'nonla', name: 'Cô Ba Nón Lá', emo: '🎋', skin: '#f7cfa6', hair: '#1a1a1a', top: '#9b5cf6', bottom: '#ffffff', shoes: '#c0392b', hairStyle: 'long', hat: 'nonla', sleeve: 1, pants: 1, extra: { aodai: '#9b5cf6' } },
  { id: 'banhmi', name: 'Cô Bánh Mì', emo: '🥖', skin: '#f6c9a0', hair: '#3a2418', top: '#ff8fb8', bottom: '#4b4478', shoes: '#ffc93d', hairStyle: 'bun', hat: 'scarfHead', hatColor: '#ff6f3c', sleeve: 0.5, pants: 1, extra: { apron: '#ff9a3c' } },
  { id: 'xeom', name: 'Chú Xe Ôm', emo: '🛵', skin: '#e8b48a', hair: '#1a1a1a', top: '#3aa357', bottom: '#5b4a3a', shoes: '#3a2a1c', hairStyle: 'short', hat: 'helmet', hatColor: '#2fbf71', face: ['mustache'], sleeve: 1, pants: 1 },
  { id: 'ngoai', name: 'Bà Ngoại', emo: '👵', skin: '#f3c9a6', hair: '#eeeef5', top: '#a86b3c', bottom: '#2b2550', shoes: '#6b4426', hairStyle: 'bun', face: ['glasses', 'blush'], sleeve: 1, pants: 1, extra: { belt: '#2b2550' } },
  { id: 'baove', name: 'Bác Bảo Vệ', emo: '👮', skin: '#e8b48a', hair: '#2a1a14', top: '#c9b27a', bottom: '#6b5a3a', shoes: '#1d1648', hairStyle: 'short', hat: 'cap', hatColor: '#2b3a6b', face: ['mustache'], sleeve: 0.5, pants: 1, extra: { whistle: true, badge: true, belt: '#3a2a1c' } },
  { id: 'shipper', name: 'Anh Shipper', emo: '📦', skin: '#ffd2a6', hair: '#1a1a1a', top: '#ff8a1f', bottom: '#2b2550', shoes: '#ffffff', hairStyle: 'short', hat: 'fullhelmet', hatColor: '#ff8a1f', sleeve: 1, pants: 1, extra: { box: '#ff8a1f' } },
  { id: 'chef', name: 'Vua Đầu Bếp', emo: '👨‍🍳', skin: '#ffd2a6', hair: '#6b4426', top: '#ffffff', bottom: '#2b2550', shoes: '#1d1648', hairStyle: 'short', hat: 'chef', face: ['curly'], sleeve: 1, pants: 1, extra: { scarf: '#ff3d4f', apron: '#ffffff' } },
  { id: 'chotdon', name: 'Chị Chốt Đơn', emo: '📱', skin: '#fcd2b0', hair: '#a8452a', top: '#ff3d8b', bottom: '#1d1648', shoes: '#ffc93d', hairStyle: 'wavy', face: ['blush'], sleeve: 0.3, pants: 0.4, extra: { dress: '#ff3d8b', chain: true } },
  { id: 'scientist', name: 'Giáo Sư Khùng', emo: '🧪', skin: '#fbcca6', hair: '#eeeef5', top: '#4dabf7', bottom: '#5b6478', shoes: '#3a2a1c', hairStyle: 'messy', face: ['glasses'], sleeve: 1, pants: 1, extra: { coat: '#ffffff', tie: '#ff3d4f' } },
  { id: 'doctor', name: 'Bác Sĩ', emo: '🩺', skin: '#f6c9a0', hair: '#2a1a14', top: '#3ccf9e', bottom: '#3ccf9e', shoes: '#ffffff', hairStyle: 'slick', hat: 'mirror', sleeve: 1, pants: 1, extra: { coat: '#ffffff' } },
  { id: 'boss', name: 'Tổng Tài', emo: '😎', skin: '#f6c9a0', hair: '#1a1a1a', top: '#22223a', bottom: '#22223a', shoes: '#0d0d18', hairStyle: 'slick', face: ['shades'], sleeve: 1, pants: 1, extra: { tie: '#ff3d4f' } },
  { id: 'idol', name: 'Idol Nhí', emo: '🎤', skin: '#fcd2b0', hair: '#ffcf4d', top: '#ff6fb5', bottom: '#ffffff', shoes: '#ff6fb5', hairStyle: 'pigtails', face: ['blush'], sleeve: 0.3, pants: 0.3, extra: { dress: '#ffffff', star: '#ffc93d' } },
  { id: 'rocker', name: 'Rocker', emo: '🎸', skin: '#fbcca6', hair: '#ff3d8b', top: '#1d1648', bottom: '#2b2550', shoes: '#ff3d4f', hairStyle: 'mohawk', face: ['shades'], sleeve: 0.35, pants: 1, extra: { chain: true } },
  { id: 'rapper', name: 'Rapper', emo: '🧢', skin: '#c98b5e', hair: '#1a1a1a', top: '#8b5cf6', bottom: '#2b2550', shoes: '#ffffff', hairStyle: 'short', hat: 'capBack', hatColor: '#ffc93d', sleeve: 1, pants: 1, extra: { chain: true } },
  { id: 'gamer', name: 'Game Thủ', emo: '🎮', skin: '#fcd2b0', hair: '#4b2e1a', top: '#2fbf71', bottom: '#2b2550', shoes: '#ffffff', hairStyle: 'messy', hat: 'phones', hatColor: '#1d1648', face: ['glasses'], sleeve: 1, pants: 1 },
  { id: 'football', name: 'Cầu Thủ', emo: '⚽', skin: '#e8b48a', hair: '#1a1a1a', top: '#ff3d4f', bottom: '#ffffff', shoes: '#ffc93d', hairStyle: 'spiky', hat: 'band', hatColor: '#ffffff', sleeve: 0.3, pants: 0.3, legs: '#ff3d4f' },
  { id: 'farmer', name: 'Bác Nông Dân', emo: '🌾', skin: '#d99b6c', hair: '#1a1a1a', top: '#7a5230', bottom: '#5b4a3a', shoes: '#3a2a1c', hairStyle: 'short', hat: 'nonla', sleeve: 1, pants: 0.7, extra: { scarf: '#1d1648' } },
  { id: 'ongdo', name: 'Ông Đồ', emo: '📜', skin: '#f3c9a6', hair: '#eeeef5', top: '#2f6bff', bottom: '#ffffff', shoes: '#1d1648', hairStyle: 'bald', hat: 'turban', hatColor: '#1d1648', face: ['beard', 'glasses'], sleeve: 1, pants: 1, extra: { aodai: '#2f6bff' } },
  { id: 'fire', name: 'Lính Cứu Hoả', emo: '🧑‍🚒', skin: '#ffd2a6', hair: '#6b4426', top: '#ffb63d', bottom: '#ffb63d', shoes: '#1d1648', hairStyle: 'short', hat: 'fire', hatColor: '#ff3d4f', sleeve: 1, pants: 1, gloves: '#1d1648', extra: { belt: '#ffe14d' } },
  { id: 'astro', name: 'Phi Hành Gia', emo: '🚀', skin: '#fbcca6', hair: '#3a2a1c', top: '#f2f4ff', bottom: '#f2f4ff', shoes: '#8b93b8', hairStyle: 'short', hat: 'bubble', sleeve: 1, pants: 1, gloves: '#ffffff', extra: { pack: '#dfe3f5', badge: true } },
  { id: 'hero', name: 'Siêu Nhân Đụt', emo: '🦸', skin: '#ffd2a6', hair: '#1d1648', top: '#2f6bff', bottom: '#ff3d4f', shoes: '#ff3d4f', hairStyle: 'ahoge', hat: 'band', hatColor: '#ff3d4f', sleeve: 1, pants: 0.2, legs: '#2f6bff', gloves: '#ffffff', extra: { cape: '#ff3d4f', star: '#ffc93d', belt: '#ffc93d' } },
  { id: 'ninja', name: 'Ninja Hụt', emo: '🥷', skin: '#ffd2a6', hair: '#14102e', top: '#2b2550', bottom: '#2b2550', shoes: '#14102e', hairStyle: 'bald', hat: 'ninja', hatColor: '#2b2550', sleeve: 1, pants: 1, extra: { belt: '#ff3d4f' } },
  { id: 'pirate', name: 'Cướp Biển', emo: '🏴‍☠️', skin: '#e8b48a', hair: '#2a1a14', top: '#ffffff', bottom: '#2b2550', shoes: '#3a2a1c', hairStyle: 'short', hat: 'tricorn', hatColor: '#1d1648', face: ['patch', 'beard'], beard: '#2a1a14', sleeve: 1, pants: 0.75, extra: { belt: '#ff3d4f', vest: '#c0392b' } },
  { id: 'king', name: 'Vua Hề', emo: '👑', skin: '#ffd2a6', hair: '#a86b3c', top: '#8b5cf6', bottom: '#ffc93d', shoes: '#ff3d4f', hairStyle: 'short', hat: 'crown', face: ['curly'], sleeve: 1, pants: 1, extra: { cape: '#e8344a', belt: '#ffc93d' } },
  { id: 'princess', name: 'Công Chúa', emo: '👸', skin: '#fcd2b0', hair: '#ffcf4d', top: '#ff8fc8', bottom: '#ff8fc8', shoes: '#ffffff', hairStyle: 'long', hat: 'tiara', face: ['blush'], sleeve: 0.3, pants: 1, extra: { dress: '#ff8fc8' } },
  { id: 'vampire', name: 'Bá Tước Ma', emo: '🧛', skin: '#e9e4f5', hair: '#1a1a1a', top: '#ffffff', bottom: '#1d1648', shoes: '#1d1648', hairStyle: 'slick', face: ['fangs'], sleeve: 1, pants: 1, extra: { cape: '#1d1648', collar: '#e8344a', vest: '#e8344a' } },
  { id: 'santa', name: 'Ông Già Noel', emo: '🎅', skin: '#ffd2a6', hair: '#ffffff', top: '#e8344a', bottom: '#e8344a', shoes: '#1d1648', hairStyle: 'short', hat: 'santa', face: ['beard', 'blush'], beard: '#ffffff', sleeve: 1, pants: 1, gloves: '#1d1648', extra: { belt: '#1d1648', belly: '#e8344a' } },
  { id: 'bear', name: 'Gấu Bông', emo: '🧸', skin: '#ffd2a6', hair: '#c98b52', top: '#c98b52', bottom: '#c98b52', shoes: '#8a5a2e', hairStyle: 'bald', hat: 'hood', hood: 'bear', hatColor: '#c98b52', sleeve: 1, pants: 1, gloves: '#c98b52', extra: { belly: '#f2d2a9' } },
  { id: 'cat', name: 'Mèo Mập', emo: '🐱', skin: '#fcd2b0', hair: '#ff9a3c', top: '#ff9a3c', bottom: '#ff9a3c', shoes: '#ffffff', hairStyle: 'bald', hat: 'hood', hood: 'cat', hatColor: '#ff9a3c', sleeve: 1, pants: 1, gloves: '#ffffff', extra: { belly: '#fff1e0' } },
  { id: 'dino', name: 'Khủng Long', emo: '🦖', skin: '#ffd2a6', hair: '#2fbf71', top: '#2fbf71', bottom: '#2fbf71', shoes: '#1f8f52', hairStyle: 'bald', hat: 'hood', hood: 'dino', hatColor: '#2fbf71', sleeve: 1, pants: 1, gloves: '#2fbf71', extra: { belly: '#d9f99d' } },
  { id: 'frog', name: 'Ếch Ộp', emo: '🐸', skin: '#fcd2b0', hair: '#7bd148', top: '#7bd148', bottom: '#7bd148', shoes: '#ffc93d', hairStyle: 'bald', hat: 'hood', hood: 'frog', hatColor: '#7bd148', sleeve: 1, pants: 1, gloves: '#7bd148', extra: { belly: '#e9ffd0' } },
  { id: 'dog', name: 'Cậu Vàng', emo: '🐶', skin: '#fcd2b0', hair: '#e8b04a', top: '#e8b04a', bottom: '#e8b04a', shoes: '#8a5a2e', hairStyle: 'bald', hat: 'hood', hood: 'dog', hatColor: '#e8b04a', sleeve: 1, pants: 1, gloves: '#e8b04a', extra: { belly: '#fff1d6', scarf: '#2f8bff' } },
  { id: 'bride', name: 'Cô Dâu', emo: '👰', skin: '#fcd2b0', hair: '#4b2e1a', top: '#ffffff', bottom: '#ffffff', shoes: '#ffffff', hairStyle: 'bun', hat: 'veil', sleeve: 0.3, pants: 1, face: ['blush'], extra: { dress: '#ffffff' } },
  { id: 'beanie', name: 'Anh Chàng Lạnh', emo: '🧣', skin: '#ffd2a6', hair: '#6b4426', top: '#38b2ff', bottom: '#2b2550', shoes: '#ff4d6d', hairStyle: 'short', hat: 'beanie', hatColor: '#ff4d6d', sleeve: 1, pants: 1, face: ['freckles'], extra: { scarf: '#ffc93d' } },
];
export const CHAR_MAP = Object.fromEntries(CHARS.map((c) => [c.id, c]));
